<?xml version="1.0" encoding="utf-8"?><Database Name="aspnet-PassGeneralsModels-20160112062155" Class="AvailabilityDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\aspnet-PassGeneralsModels-20160112062155.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="aspnet_PassGeneralsModels_20160112062155ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Availability" Member="Availabilities">
    <Type Name="Availability">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="start_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="end_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>